version: '3'
services:
  ui_backend:
    build: ./ui_backend
    ports:
      - "5000:5000"  # Maps host port 5000 to container port 5000
    depends_on:
      - ai_backend
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs  # Mounts outputs folder for persistence
  ai_backend:
    build: ./ai_backend
    ports:
      - "5001:5001"  # Maps host port 5001 to container port 5001
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs  # Mounts outputs folder for persistence