services:
  ai_backend:
    build: ./ai_backend
    ports:
      - "5001:5001"
    volumes:
      - ./outputs:/app/outputs  # Mount for saving output.jpg
  ui_backend:
    build: ./ui_backend
    ports:
      - "5000:5000"
    depends_on:
      - ai_backend  # Starts ai_backend first